apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    purpose: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      purpose: example
  template:
    metadata:
      labels:
        app: prometheus
        purpose: example
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
          - containerPort: 9090
            name: promport
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-example-service
  labels:
    mrmcpat: test
spec:
  selector:
    app: prometheus
    purpose: example
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090